In [1]:
import selenium
from selenium import webdriver
import csv
import pandas as pd

In [2]:
driver = webdriver.Chrome()

In [3]:
property_shark = 'https://www.propertyshark.com/mason/Street-Index/CA/San-Diego-County/'
# driver.get(property_shark)

In [4]:
addresses = "resources/address.csv"
address_df = pd.read_csv(addresses)

In [5]:
address_df

    Zip_Code      Street_Name  House_Number  Street_Name_URL
0      91905    Fauntleroy Rd         39011    Fauntleroy-Rd
1      91905       Bonair Way         39025       Bonair-Way
2      91905    Fauntleroy Rd         39133    Fauntleroy-Rd
3      91905        Fisher Rd         40495        Fisher-Rd
4      91911      Barrett Ave           950      Barrett-Ave
5      91911      Barrett Ave           960      Barrett-Ave
6      91911      Barrett Ave           994      Barrett-Ave
7      91911      Cardinal Pl          1280      Cardinal-Pl
8      91911      Cardinal Pl          1293      Cardinal-Pl
9      91911  Diablo Point CT          1572  Diablo-Point-CT
10     92037       Bonair Way           734       Bonair-Way
11     92037    Fauntleroy Rd           774    Fauntleroy-Rd
12     92037       Bonair Way           711       Bonair-Way

In [6]:
# for loop on zip code 
    # create databases that filters by each zipcode
    # make that database equal a variable 
    # store that variable in a list

In [7]:
zip_list = []
street_list = []
number_list = []
for i, row in address_df.iterrows():
    i = row["Zip_Code"]
    zip_list.append(i)
    i = row["Street_Name"]
    street_list.append(i)
    i = row["House_Number"]
    number_list.append(i)
    #df_filtered = address_df.query(f'Zip_Code=={i}')
    #Street_Name = row['Street Name']
    #House_Number = row['House Number']
    #driver.get(property_shark+str(zip_code))
# street_list

In [8]:
# zip_list = list(dict.fromkeys(zip_list))
# street_list = list(dict.fromkeys(street_list))
# number_list = list(dict.fromkeys(number_list))

In [9]:
# zip_list

In [10]:
# street_list

In [11]:
# number_list

In [12]:
addresses = []
neighborhood_list = []
Achorage_list = []
square_footage_list = []
year_built_list = []
Parcel_ID_list = []
Property_class_list = []
Legal_description_list = []
units_list = []
bath_list = []
bed_list = []

# for zipcode in zip_list:
#     zipcode = str(zipcode)
#     zip_shark = property_shark + zipcode
#     driver.get(zip_shark)
#     for street in street_list:
#         try: 
#             street = str(street)
#             street_code = driver.find_element_by_partial_link_text(street)
#             street_code.click()
#             for address in number_list:
for i, row in address_df.iterrows():
    zip_code = str(row["Zip_Code"])
    street_name = str(row["Street_Name"])
    address = str(row["House_Number"])
    street_URL = str(row["Street_Name_URL"])
    zip_shark = property_shark + zip_code +'/' + street_URL
    driver.get(zip_shark)
    try: 
        address_link = str(f"{address} {street_name}")
        address_code = driver.find_element_by_link_text(address_link)
        address_code.click()
        try:
            street_number = driver.find_element_by_xpath('//*[@id="nationwide/property_details_content"]/div/div[1]/table/tbody/tr[1]/td/table/tbody/tr/td').text
            addresses.append(street_number)
        except:
            addresses.append("NA")
        try:
            square_footage = driver.find_element_by_xpath('//*[@id="nationwide/property_details_content"]/div/div[2]/table/tbody/tr[3]/td/table/tbody/tr/td').text
            square_footage_list.append(square_footage)
        except:
            square_footage_list.append("NA")
        try:
            year_built = driver.find_element_by_xpath('//*[@id="nationwide/property_details_content"]/div/div[2]/table/tbody/tr[4]/td/table/tbody/tr/td').text
            year_built_list.append(year_built)
        except:
            year_built_list.append("NA")
        try:
            Parcel_ID = driver.find_element_by_xpath('//*[@id="nationwide/property_details_content"]/div/div[1]/table/tbody/tr[3]/td/table/tbody/tr/td').text
            Parcel_ID_list.append(Parcel_ID)
        except:
            Parcel_ID_list.append("NA")
        try: 
            Property_class = driver.find_element_by_xpath('//*[@id="nationwide/property_details_content"]/div/div[2]/table/tbody/tr[1]/td/table/tbody/tr/td').text
            Property_class_list.append(Property_class)
        except:
            Property_class_list.append("NA")
        try:
            Legal_description = driver.find_element_by_xpath('//*[@id="nationwide/property_details_content"]/div/div[1]/table/tbody/tr[4]/td/table/tbody/tr/td').text
            Legal_description_list.append(Legal_description)
        except:
            Legal_description_list.append("NA")
        try: 
            units = driver.find_element_by_xpath('//*[@id="nationwide/property_details_content"]/div/div[2]/table/tbody/tr[5]/td/table/tbody/tr/td').text
            units_list.append(units)
        except:
            units_list.append("NA")
        try:
            bath = driver.find_element_by_xpath('//*[@id="nationwide/property_details_content"]/div/div[2]/table/tbody/tr[7]/td/table/tbody/tr/td').text
            bath_list.append(bath)
        except:
            bath_list.append("NA")
        try:
            bed = driver.find_element_by_xpath('//*[@id="nationwide/property_details_content"]/div/div[2]/table/tbody/tr[6]/td/table/tbody/tr/td').text
            bed_list.append(bed)
        except:
            bed_list.append("NA")
        try:
            Neighborhood = driver.find_element_by_xpath('//*[@id="nationwide/property_details_content"]/div/div[1]/table/tbody/tr[5]/td/table/tbody/tr/td').text
            neighborhood_list.append(Neighborhood)
        except:
            neighborhood_list.append("NA")
        try:
            Achorage = driver.find_element_by_xpath('//*[@id="nationwide/property_details_content"]/div/div[1]/table/tbody/tr[5]/td/table/tbody/tr/td').text
            Achorage_list.append(Achorage)
        except:
            Achorage_list.append("NA")
        print("Successs")
    except:
        print(f"{address} {street_name} is Not applicable")

Successs
39025 Bonair Way is Not applicable
Successs
Successs
Successs
Successs
Successs
Successs
Successs
Successs
Successs
774 Fauntleroy Rd is Not applicable
Successs

In [13]:
# neighborhood_list

In [14]:
Property_shark_df = pd.DataFrame({'address': addresses, 'neighborhood': neighborhood_list, 'Acorage': Achorage_list, 'SQFT': square_footage_list, 'year built': year_built_list, 'Parcel ID': Parcel_ID_list, 'Property Class': Property_class_list, 'Legal Description': Legal_description_list, 'units': units_list, 'bath': bath_list, 'bed':bed_list})
Property_shark_df

,address,neighborhood,Acorage,SQFT,year built,Parcel ID,Property Class,Legal Description,units,bath,bed
0,"39011 Fauntleroy Rd,\nBoulevard, CA 91905",NA,NA,Subscribe,NA,612-010-81-00,12.78,PAR 4*PAR B PER DOC05-0823289 IN,NA,NA,NA
1,"39133 Fauntleroy Rd,\nBoulevard, CA 91905",NA,NA,Subscribe,"1,645",612-010-80-00,4.04,PAR 2*PAR A PER DOC05-0823289 IN PAR 4&ALL OF,2005,3,1
2,"40495 Fisher Rd,\nBoulevard, CA 91905",NA,NA,Subscribe,NA,612-090-57-00,44.26,SEC 28-17-7E*SWQ*SWQ OF,NA,NA,NA
3,"950 Barrett Ave,\nChula Vista, CA 91911",Castle Park,Castle Park,Subscribe,"2,000",575-241-08-00,0.29,LOT 101*,1955,4,1
4,"960 Barrett Ave,\nChula Vista, CA 91911",Castle Park,Castle Park,Subscribe,"1,544",575-241-10-00,0.25,LOT 99*,1955,4,1
5,"994 Barrett Ave,\nChula Vista, CA 91911",Castle Park,Castle Park,Subscribe,"1,810",575-232-17-00,0.22,LOT 92*,1955,3,1
6,"1280 Cardinal Pl,\nChula Vista, CA 91911",Sunbow,Sunbow,Subscribe,"1,814",620-651-10-00,0.34,LOT 68,1977,4,1
7,"1293 Cardinal Pl,\nChula Vista, CA 91911",Sunbow,Sunbow,Subscribe,"1,480",620-651-13-00,0.18,LOT 65,1977,3,1
8,"1572 Diablo Point Ct,\nChula Vista, CA 91911",Sunbow,Sunbow,"2,262",1979,644-221-18-00,Single Family Residence (11),LOT 257,1,2.5,4
9,"734 Bonair Way,\nLA Jolla, CA 92037",Beach - Barber,Beach - Barber,480,1948,351-370-39-00,Single Family Residence (11),PAR 2,1,1,1
10,"711 Bonair Way,\nLA Jolla, CA 92037",Beach - Barber,Beach - Barber,"1,505",1990,351-370-29-00,Single Family Residence (11),BLK D*LOT 10*ELY 45 FT OF NLY 55 FT OF,1,3,2

In [15]:
Property_shark_df.to_csv(r'C:\Users\Jeffh\Documents\Bootcamp\ETL_Project\San-Diego-Housing-Market\zillow.csv')